  - name: Copy mongo repo to yum.repos.d
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: Copy catalogue.js to yum.repos.d
    ansible.builtin.copy:
      src: catalogue.js
      dest: /tmp/catalogue.js

  - name: Install mongodb
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: start and enable mongodb
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  - name: allow remote conncections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: start and enable mongodb
    ansible.builtin.service:
      name: mongod
      state: restarted
  
  - name : load catalogue data
    ansible.builtin.shell: mongo --host localhost < /tmp/catalogue.js 