  - name: Disable current mySQL Version
    ansible.builtin.command: yum module disable mysql -y

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: Install MySQL Community Server package
    ansible.builtin.yum:
      name: mysql-community-server
      state: installed

  - name: Start service catalogue
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true

  - name: setup mysql root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1